### PR TITLE
Set fetch depth as well as clone depth for torture test suite

### PR DESCRIPTION
**Pull request by dschuff**
Needed if we want to keep the shallow clone shallow.

### CODE REVIEW

**Comment by dschuff** [comment]
It looks like the fetches are taking a lot longer for me now than previously; is anyone else seeing this? May be the case on the buildbot too. I reread the man page for `git fetch` and it seems to imply that it may not be necessary anyway if the clone was created as a shallow clone anyway.

**Comment by sbc100** [comment]
I think you might be right... maybe a fetch with --depth=1 will actually end up downloading a lot more because it can't incrementally build on a previously clone/fetch.

**Comment by jfbastien** [comment]
The GCC clone depth is 1000, and then we checkout a particular revision to avoid torture test cahnges breaking things. Is that revision more than 1000 revisions in the past?

**Comment by dschuff** [comment]
No I don't think so; I just noticed that fetch was being slow when I
bootstrapped it on my laptop, and thought it was maybe because the fetch
was fetching more than was originally cloned.

**Pull request merged**
