### PR TITLE
Update to Node LTS 12.18.1

### PR DESCRIPTION
**Pull request by dschuff**
This version has V8 v7.8, and in particular includes support for the wasm
fence instruction.

### CODE REVIEW

**Comment by kripken** [comment]
This is a different node version than the emsdk installs by default, which seems like a downside?

**Comment by sbc100** [comment]
I'm ok with landing this if we agree to also update the emsdk version to 12.18.1.  (There is a script in emsdk/scripts which should make this easy enough).

**Comment by dschuff** [comment]
Ah right, that's my intention, to also update emsdk.

**Comment by dschuff** [comment]
If I land this, it will test this version on chromium CI. will emscripten CI also pick that up, or does it use emsdk for that?

**Comment by sbc100** [comment]
I think this change will only effect the waterfall itself, not emscripten, or emsdk.

**Comment by dschuff** [comment]
Ok, makes sense. I'll go ahead and land it, and we can make sure at least those tests are unaffected.

**Pull request merged**
