### PR TITLE
Remove support for python2

### PR DESCRIPTION
**Pull request by sbc100**
Seems like the time has come

### CODE REVIEW

**Comment by dschuff** [comment]
We haven't actually pulled the trigger on Py2 in emscripten yet, correct? Do we want to wait on this until we do that?

**Comment by sbc100** [comment]
My plan was to start removing python2 and using py3-only features one project at time.   

I did wabt already: https://github.com/WebAssembly/wabt/pull/1321

Next up is binaryen.   Not that for wabt and binaryn the dependency is only on those that build the projects, not those that run them.

I imagine emscripten and emsdk will probably take longer since we have more end users running the python code directly.

Maybe I'm misunderstanding.  Why would we want to block converting this project to python3 on converting emscripten?

**Comment by dschuff** [comment]
If we need to run Python2 on our CI in order to test emscripten in python2, then it might be convenient to have the waterfall support python2. Otherwise we'd have to run the waterfall under python3 and then invoke python2 explicitly when running emscripten (and make sure that the environment is correct e.g. using vpython if applicable). Not impossible, just maybe more trouble than just keeping python2 in the waterfall.

**Comment by dschuff** [comment]
(I guess this is less of a problem on CircleCI than it is on chromium CI? So maybe we just only use py3 on Chromium CI?)

**Comment by sbc100** [comment]
I think its fine for the test running (the waterfall) to be python3 while the system under test (emscripten) to be using python2.

If we want to be able to test emcc with both python3 and python3 then we have to pick just one to run the waterfall code under, right?

**Comment by dschuff** [comment]
I think currently emcc will just run under whatever we run the waterfall under, but I'm not sure if that's just because chromium CI only set up the environment for one of them? Currently the waterfall at least runs the emscripten test runner explicitly under sys.executable.

**Comment by sbc100** [comment]
Yes, it goes look like it used `sys.executable` to run `tests/runner.py` which in turn will use `sys.executable` to run `emcc.py`.

However if we want to support both we probably want to control that explicitly from build.py..  I think `sys.executable` would not be relevant in that world anyway, once we make it explicit.  

I still this this PR is fine, if we want to being back python2 testing we would just modify the callsite where `runner.py` is run.

**Comment by dschuff** [comment]
Yeah, agreed.

**Pull request merged**
