### PR TITLE
Test running .wasm files in d8

### PR DESCRIPTION
**Pull request by jfbastien**
The waterfall compiles the GCC C torture tests using LLVM, links the resulting .s assembly files using binaryen's s2wasm, assembles the resulting .wast s-expression file using sexpr-wasm, and now executes the resulting .wasm binary file using V8's d8 shell.

wasm.js implements the minimal C library support that's needed for the torture tests: exit and abort. The torture tests are otherwise self-checking.

I've triaged the failures, but haven't put any effort into fixing any of them right now.

You can reproduce my results without running the entire ./src/build.py script (which downloads and builds a bunch of sources) by doing:
  ./src/execute_files.py --runner ./src/work/wasm-install/bin/d8 --files ./src/work/torture-s2wasm-sexpr-wasm/\*.wasm --fails ./src/test/d8_known_gcc_test_failures.txt --wasmjs ./src/test/wasm.js

You can download pre-assembled .wasm files from the waterfall at:
  https://build.chromium.org/p/client.wasm.llvm/console
Pick a green build, [download] link from 'Assemble LLVM Torture with s2wasm-sexpr-wasm', the URL is similar to:
  https://storage.googleapis.com/wasm-llvm/builds/git/wasm-torture-s2wasm-sexpr-wasm-BUILDNUMBER.tbz2

### CODE REVIEW

**Comment by jfbastien** [comment]
I tested locally and this does what I expect, I'll therefore commit so it starts running on the waterfall but would appreciate comments from @titzer and @binji on how to improve this.

**Comment by binji** [comment]
I'm seeing this:
```
Ran 1041 tests.
Got 1041 successes.
Got 0 failures.
Expected 0 failures.
```
Am I looking in the wrong place, or are there no failures?

**Comment by jfbastien** [comment]
I get this:
>  Ran 1041 tests.
>  Got 838 successes.
>  Got 203 failures.
>  Expected 203 failures.
>  Got 203 expected failures in 6 similarity groups.
>  Got 0 unexpected failures in 0 similarity groups.
>  Got 0 unexpected successes.

You should at least get the expected failures from d8_known_gcc_test_failures.txt. Which command line did you run?

**Comment by jfbastien** [comment]
It just finished running properly on the waterfall:
https://build.chromium.org/p/client.wasm.llvm/builders/linux/builds/2228/steps/Execute%20LLVM%20Torture%20with%20d8/logs/stdio

**Comment by binji** [comment]
I was looking at the wrong step.

**Pull request merged**
