### PR TITLE
Split LLVM Regression tests into a separate step from the LLVM build

### PR DESCRIPTION
**Pull request by dschuff**
This will allow splitting into separate build steps on recipes-based bots.

### CODE REVIEW

**Comment by sbc100** [comment]
Maybe split out v8 tests and then we can remove the "--no-tool-test" option too?

**Comment by dschuff** [comment]
Or we could just leave the v8 tests out. I don't think they are particularly valuable, they've basically never failed on our waterfals.

**Comment by sbc100** [comment]
Sure.  Either way we can remove the `--no-tool-test` option (do we run wabt tests?)

**Comment by dschuff** [comment]
yeah, we don't run wabt tests either

**Comment by dschuff** [comment]
I'll land this and do that in a followup CL.

**Pull request merged**
