### PR TITLE
Compile JSC on Windows and Linux as well

### PR DESCRIPTION
**Pull request by mathiasbynens**
CC @dschuff @jfbastien

Ref. https://github.com/v8/web-tooling-benchmark/pull/29#discussion_r155831751

### CODE REVIEW

**Comment by sbc100** [comment]
Won't you need to remove the `no_windows` and `no_linux` args from line 1430? 

Also, you'll need to make the use of xcrun conditional won't you?  (since it doesn't exist on non-mac).  Maybe xcrun isn't needed?  Its not used for other cmake runs in this file.

**Comment by dschuff** [comment]
I'll give this a try locally.

**Comment by mathiasbynens** [comment]
> Won't you need to remove the `no_windows` and `no_linux` args from line 1430?

Yes! Done.

I don’t feel qualified to deal with the `xcrun` issue, to be honest. Feel free to amend this patch.

**Comment by dschuff** [comment]
Closing this as obsolete, and because we are moving the code (see #698). If there is an issue with the build scripts, please file an issue against [EMSDK](https://github.com/emscripten-core/emsdk/)

**Pull request closed without merging**
