### PR TITLE
Add 930529-1.c at -O2 to known failures

### PR DESCRIPTION
**Pull request by sbc100**

### CODE REVIEW

**Comment by jgravelle-google** [comment]
The patch I had staged looked like:
```
# Clang optimizing loop into infinite loop for -O2
930529-1.c.s.wast.wasm O2
930529-1.c.o.wasm O2
930529-1.c.js emwasm,O3 # asm2wasm uses different clang
```

Which is to say it would be nice to have a bit more detail, to merge them into the same root cause, and to also disable the emwasm -O3 version while we're at it.

**Comment by sbc100** [comment]
Want to just upload yours?

**Comment by jgravelle-google** [comment]
sgtm

**Comment by jgravelle-google** [comment]
https://github.com/WebAssembly/waterfall/pull/257

**Pull request closed without merging**
