### PR TITLE
Use tar command rather than python's tarfile to extract xz files

### PR DESCRIPTION
**Pull request by sbc100**

### CODE REVIEW

**Comment by dschuff** [comment]
That's odd, was this broken before? The prebuilt node.js is xz already isn't it?

**Comment by sbc100** [comment]
Yeah.. looks like the this is has been broken for a while, but the waterfall stayed green until I just did a clobber build.

**Comment by sbc100** [comment]
I think you broke it in #148 :)

**Comment by dschuff** [comment]
Yep, sure looks like it.

**Pull request merged**
