### PR TITLE
Test running refactoring

### PR DESCRIPTION
**Pull request by jgravelle-google**
* Add a Test class to mirror Build and Sync steps, unify filtering logic
* Add tests to --help message
* Add more details to error messages when sync/build/testing a nonexistent step

### CODE REVIEW

**Comment by sbc100** [comment]
Nice. I was working on the exact same change :)

BTW, I think you lost the cleanups I made in #91 somehow.

**Comment by jgravelle-google** [comment]
I started working on it because I thought it was the way to implement #92. It doesn't quite cover all the cases to fix that, but it still seemed worthwhile to do.

And I think that's because I started my branch before you merged those? Or I was lazy about syncing. Your cleanups are still on master, so I think we're good.

**Comment by sbc100** [comment]
I think some changes were lost somehow (this change re-introduced `emscripten+wasm backend` which I had removed).

**Comment by jgravelle-google** [comment]
Ah, you're right

I'd moved the tests, and didn't think too hard about why that would cause a merge conflict. My bad!

**Pull request merged**
