### PR TITLE
Update expectations after wasi-libc added signal emulation

### PR DESCRIPTION
**Pull request by sbc100**
See https://github.com/WebAssembly/wasi-libc/pull/183

### CODE REVIEW

**Comment by sbc100** [comment]
Landing TBR to green the waterfall.

**Comment by tlively** [comment]
If a preprocessor define and a linker flag are necessary to use the signal emulation, why did the waterfall break?

**Comment by sbc100** [comment]
The think that test was failing to compile because the signal macros were not previously defined.  With this change they are defined (even without the _WASI_EMULATED_SIGNAL).

I think _WASI_EMULATED_SIGNAL guards the declaration of the `signal` function, but not the individual signal macros themselves.

**Comment by sunfishcode** [comment]
_WASI_EMULATED_SIGNAL does guard the signal macros too. Possibly the difference is that previously the signal macros were defined by default (though not very useful) and now they're not.

**Comment by sbc100** [comment]
Yup that sounds like it.    Without adding the macro, this change removed the signal definitions.

**Pull request merged**
