### PR TITLE
Use emscripten's install.py to copy emscripten

### PR DESCRIPTION
**Pull request by sbc100**

### CODE REVIEW

**Comment by sbc100** [comment]
Oh darn, I forgot about that.  I was hoping just the linux bot would be able to install emscripten and that could be installed on mac and windows... I forgot we do monolithic builds now :(

**Comment by dschuff** [comment]
The system we use for the PNaCl toolchain can do that, but I'm not sure I want to import that here, it's 10x more complex.

**Comment by sbc100** [comment]
If we switch back to a component system in emsdk we could do this... but that is a bunch of work.

**Comment by sbc100** [comment]
Any chance we can start depending on WSL on windows any time soon?

**Comment by dschuff** [comment]
Do they make it easy to build windows binaries that don't need WSL to run?
not sure about chrome infra though, I doubt they have it now.

**Comment by dschuff** [comment]
Also it wouldn't really help for the case where we actually want to run tests on windows, in an environment like our users have, right? We still need to copy the new emscripten files somehwere to use them for tests.

**Pull request merged**
