### PR TITLE
Add expected failure for another test with zero sized symbol

### PR DESCRIPTION
**Pull request by sbc100**
These should be fixed once we land https://reviews.llvm.org/D39107

### CODE REVIEW

**Comment by aheejin** [comment]
I don't know much about the context of https://reviews.llvm.org/D39107, but if you are going to land that soon, do we need this?

**Comment by sbc100** [comment]
I want to get the waterfall green first ideally.

**Comment by sbc100** [comment]
Since its been while since we had a green build

**Comment by dschuff** [comment]
Except the compiler_rt build is still broken, so nothing beyond that is
even building, no? Do we need a newer version of CMake?

**Pull request merged**
