### PR TITLE
Download MSVC 2010 redist DLL for closure on Windows

### PR DESCRIPTION
**Pull request by dschuff**

### CODE REVIEW

**Comment by sbc100** [comment]
maybe not needed if we land this? : https://github.com/emscripten-core/emscripten/pull/10328

**Comment by sbc100** [comment]
We can't expect all our users to do this right?

**Comment by dschuff** [comment]
Right; although the bit we are doing now with `npm ci` also does not affect any users. Currently we are either expecting them to manage closure completely on their own (unless emsdk handles closure?)

**Comment by dschuff** [comment]
On the flipside if we get this working we can stop using Java on our bots entirely, at the risk of diverging from the version of closure most of our users use (assuming they use Java)

**Comment by sbc100** [comment]
emsdk handles the `npm ci` so we would need to replicate this fix there too if we go with it.

I prefer sticking with java for the windows users until upstream fixes the windows package.

**Comment by sbc100** [comment]
I landed the emscripten fix so closing this one

**Pull request closed without merging**
